process FUNCTIONAL_ANNOTATION {
    tag { sample }
    label 'med_compute'

    // OPEN SOURCE FIX: Updated Prokka to 1.14.6 to resolve the Perl/Abricate conflict
    conda 'bioconda::prokka=1.14.6 bioconda::abricate=1.0.1 conda-forge::sed'
    container 'kizitodevbio/strepto-pipeline:latest'

    // Publish results: Prokka gets its own subfolder, AMR gets its own subfolder
    publishDir "${params.outdir}/functional_annotation/${sample}", mode: 'copy'

    input:
    tuple val(sample), path(fasta_file)

    output:
    // Fixed the output paths and the emit name for pipeline integration
    tuple val(sample), path("amr_results/${sample}_amr.tsv"), path("prokka_${sample}"), emit: annotation_results
    path "${sample}_annotation.log", emit: log

    script:
    """
    #!/usr/bin/env bash
    set -euo pipefail

    LOG="${sample}_annotation.log"
    TS=\$(date "+%Y-%m-%d %H:%M:%S")
    echo "[\$TS] FUNCTIONAL_ANNOTATION started for ${sample}" > "\$LOG"

    # Define directory names
    PROKKA_OUT="prokka_${sample}"
    AMR_OUT="amr_results"
    
    mkdir -p "\$PROKKA_OUT"
    mkdir -p "\$AMR_OUT"

    # 1. Run Prokka
    echo "[\$TS] Running Prokka..." >> "\$LOG"
    prokka \\
        --outdir "\$PROKKA_OUT" \\
        --prefix "${sample}" \\
        --kingdom Bacteria \\
        --genus Streptococcus \\
        --force \\
        --cpus ${task.cpus} \\
        "${fasta_file}" >> "\$LOG" 2>&1

    # 2. Run ABRicate using the FNA file generated by Prokka
    PROKKA_FNA="\$PROKKA_OUT/${sample}.fna"

    if [ -f "\$PROKKA_FNA" ]; then
        echo "[\$TS] Running ABRicate for AMR detection..." >> "\$LOG"
        # Output is directed specifically into the amr_results folder
        abricate --db card "\$PROKKA_FNA" > "\$AMR_OUT/${sample}_amr.tsv" 2>> "\$LOG"
    else
        echo "[\$TS] ERROR: Prokka failed to produce .fna file" >> "\$LOG"
        exit 1
    fi

    echo "[\$TS] Completed successfully." >> "\$LOG"
    """
}
